### ISSUE TITLE
L2: Differentiate `require` Errors in OnChainProposer Verification

### ISSUE THREAD

**Issue by fborello-lambda** [lambdaclass/ethrex#1164]
When performing a `verify` (sending/submitting the zkProof), we may encounter the error `block not committed`, even though the block has been committed and verified. If it was verified, it would also have been removed from the mapping, which would raise the `block not committed` requirement.

[OnChainProposer.sol:](https://github.com/lambdaclass/lambda_ethereum_rust/blob/b0eab8468f5e2c54e5dbb7789e35c839602d0848/crates/l2/contracts/src/l1/OnChainProposer.sol#L125)

```solidity
        require(
            blockCommitments[blockNumber].commitmentHash != bytes32(0),
            "OnChainProposer: block not committed"
        );
        require(
            blockNumber == lastVerifiedBlock + 1,
            "OnChainProposer: block already verified"
        );
```

**Comment by h3lio5** [comment]
would rearranging those require statements help? 
Because if we submit proof for a block that's already committed and verified and whose commitment was deleted, the `require(blockNumber == lastVerifiedBlock + 1, ..)` will prevent us saying you can't verify an already verified block.

**Comment by fborello-lambda** [comment]
> would rearranging those require statements help? Because if we submit proof for a block that's already committed and verified and whose commitment was deleted, the `require(blockNumber == lastVerifiedBlock + 1, ..)` will prevent us saying you can't verify an already verified block.

Yes, you are right, the proposed solution was considered but it may not be sufficient.
A more robust solution will require some research and changes. 
We are working on it.
