### ISSUE TITLE
L2: Forbid `panic`s

### ISSUE THREAD

**Issue by ilitteri** [lambdaclass/ethrex#1269]
Add the following clippy lint to all `Cargo.toml` files in the `l2` crate:

```toml
[lints.clippy]
panic = "deny"
```

and remove the `panic`s of the module if necessary.

**Comment by varun-doshi** [comment]
I can take this up.
To clarify, this would make panic throw compile time errors so that we'd have to return a proper error.
I see some functions do not have a return type. Should I add a return type of `Result<(),Error>` there?
