### ISSUE TITLE
Gas refund mismatch: 4800

### ISSUE THREAD

**Issue by lima-limon-inc** [lambdaclass/ethrex#1493]
There are 24 different test vectors that fail due to a difference of 4800 gas.

Most likely due to a problem in `sstore`.

**Comment by damiramirez** [comment]
Some gas used and refunded mismatch issues were fixed in this [PR](https://github.com/lambdaclass/ethrex/pull/1503).

**Comment by lima-limon-inc** [comment]
I'm closing this issue, it was too vague and like Damian said, some of these issues have been fixed
