### ISSUE TITLE
Add support to passing `bootnodes` as argument to the cli.

### ISSUE THREAD

**Issue by mpaulucci** [lambdaclass/ethrex#20]
The client should support passing bootnodes through the CLI. These should be comma-separated strings, i.e

`bootnodes=enode://4e5e92199ee224a01932a377160aa432f31d0b351f84ab413a8e0a42f4f36476f8fb1cbe914af0d9aef0d51665c214cf653c651c4bbd9d5550a934f241f1682b@138.197.51.181:30303, enode://143e11fb766781d22d92a2e33f8f104cddae4411a122295ed1fdb6638de96a6ce65f5b7c964ba3763bba27961738fef7d3ecc739268f3e5e771fb4c87b6234ba@146.190.1.103:30303`

We should be able to parse these as Node Records.

Ethereum package will use to create a localnet: https://github.com/lambdaclass/ethereum-package/pull/1/files#diff-79bf8330a2e72edba847d9ca9de634c4339dc13afb11636b13e0a4775119dcbbR227-R234

When using a public network, we should have the values hardcoded in code/config.

These will be used for P2P discovery

**Comment by mahmudsudo** [comment]
can i take on this please ?

**Comment by mpaulucci** [comment]
sorry @mahmudsudo , just saw this. We're planning to open this project for external contributors soon, but for now we want to move forward with our internal team.
